// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wckbbipwtelxqdaojmli.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indja2JiaXB3dGVseHFkYW9qbWxpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc1NjczNjEsImV4cCI6MjA1MzE0MzM2MX0.TMPa7kFqwOXTviXlBR6itiep8ycbMWfSQyfkLKKnXFI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);